//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputSystem/InputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Input: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Input()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputAction"",
    ""maps"": [
        {
            ""name"": ""OculusController"",
            ""id"": ""4df91c48-3101-4b68-aca4-8102ab031d88"",
            ""actions"": [
                {
                    ""name"": ""Trigger"",
                    ""type"": ""Value"",
                    ""id"": ""f973fcf7-eb32-46a4-8e24-2559a091fac2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7694f3c6-e6e5-433d-8fc8-bbb4a2e66220"",
                    ""path"": ""<XRController>{RightHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // OculusController
        m_OculusController = asset.FindActionMap("OculusController", throwIfNotFound: true);
        m_OculusController_Trigger = m_OculusController.FindAction("Trigger", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // OculusController
    private readonly InputActionMap m_OculusController;
    private List<IOculusControllerActions> m_OculusControllerActionsCallbackInterfaces = new List<IOculusControllerActions>();
    private readonly InputAction m_OculusController_Trigger;
    public struct OculusControllerActions
    {
        private @Input m_Wrapper;
        public OculusControllerActions(@Input wrapper) { m_Wrapper = wrapper; }
        public InputAction @Trigger => m_Wrapper.m_OculusController_Trigger;
        public InputActionMap Get() { return m_Wrapper.m_OculusController; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OculusControllerActions set) { return set.Get(); }
        public void AddCallbacks(IOculusControllerActions instance)
        {
            if (instance == null || m_Wrapper.m_OculusControllerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_OculusControllerActionsCallbackInterfaces.Add(instance);
            @Trigger.started += instance.OnTrigger;
            @Trigger.performed += instance.OnTrigger;
            @Trigger.canceled += instance.OnTrigger;
        }

        private void UnregisterCallbacks(IOculusControllerActions instance)
        {
            @Trigger.started -= instance.OnTrigger;
            @Trigger.performed -= instance.OnTrigger;
            @Trigger.canceled -= instance.OnTrigger;
        }

        public void RemoveCallbacks(IOculusControllerActions instance)
        {
            if (m_Wrapper.m_OculusControllerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IOculusControllerActions instance)
        {
            foreach (var item in m_Wrapper.m_OculusControllerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_OculusControllerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public OculusControllerActions @OculusController => new OculusControllerActions(this);
    public interface IOculusControllerActions
    {
        void OnTrigger(InputAction.CallbackContext context);
    }
}
